In [19]:
# 导入需要用到的库
import pandas as pd
import numpy as np

In [21]:
#创建特征列表
column_names = ['Sample code number', 'Clump Thickness', 'Unigormity og Cell Size',
                'Uniformity of Cell Shape', 'Marginal Adhesion', 'Single EpithelitalCellSize',
                'Bare Nuclei', 'Bland Chromatin', 'Normal Nucleoli', 'Mitoses','Class']

In [5]:
#读取数据
data=pd.read_csv('breast-cancer-wisconsin.data', names =column_names)
data.describe()

,Sample code number,Clump Thickness,Unigormity og Cell Size,Uniformity of Cell Shape,Marginal Adhesion,Single Epithelital CellSize,Bland Chromatin,Normal Nucleoli,Mitoses,Class
count,6.990000e+02,699.000000,699.000000,699.000000,699.000000,699.000000,699.000000,699.000000,699.000000,699.000000
mean,1.071704e+06,4.417740,3.134478,3.207439,2.806867,3.216023,3.437768,2.866953,1.589413,2.689557
std,6.170957e+05,2.815741,3.051459,2.971913,2.855379,2.214300,2.438364,3.053634,1.715078,0.951273
min,6.163400e+04,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000
25%,8.706885e+05,2.000000,1.000000,1.000000,1.000000,2.000000,2.000000,1.000000,1.000000,2.000000
50%,1.171710e+06,4.000000,1.000000,1.000000,1.000000,2.000000,3.000000,1.000000,1.000000,2.000000
75%,1.238298e+06,6.000000,5.000000,5.000000,4.000000,4.000000,5.000000,4.000000,1.000000,4.000000
max,1.345435e+07,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,4.000000

In [7]:
#对数据进行简单预处理
#将？替换为标准缺失值
data = data.replace(to_replace = '?', value = np.nan)
#去掉带有缺失值的数据
data = data.dropna(how = 'any')
#再次对数据进行描述
data.describe()

,Sample code number,Clump Thickness,Unigormity og Cell Size,Uniformity of Cell Shape,Marginal Adhesion,Single Epithelital CellSize,Bland Chromatin,Normal Nucleoli,Mitoses,Class
count,6.830000e+02,683.000000,683.000000,683.000000,683.000000,683.000000,683.000000,683.000000,683.000000,683.000000
mean,1.076720e+06,4.442167,3.150805,3.215227,2.830161,3.234261,3.445095,2.869693,1.603221,2.699854
std,6.206440e+05,2.820761,3.065145,2.988581,2.864562,2.223085,2.449697,3.052666,1.732674,0.954592
min,6.337500e+04,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000
25%,8.776170e+05,2.000000,1.000000,1.000000,1.000000,2.000000,2.000000,1.000000,1.000000,2.000000
50%,1.171795e+06,4.000000,1.000000,1.000000,1.000000,2.000000,3.000000,1.000000,1.000000,2.000000
75%,1.238705e+06,6.000000,5.000000,5.000000,4.000000,4.000000,5.000000,4.000000,1.000000,4.000000
max,1.345435e+07,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,4.000000

In [10]:
#对数据进行分割
from sklearn.model_selection import train_test_split
#75%的数据用做训练集，25%的数据用做测试集
X_train, X_test, y_train, y_test = train_test_split(data[column_names[1:10]], 			    data[column_names[10]], test_size = 0.25, 			    random_state = 33)

#查验训练样本的数量和类别分布
y_train.value_counts()

#查验测试样本的数量和类别分布
y_test.value_counts()

2    100
4     71
Name: Class, dtype: int64

In [11]:
#导入需要用到的算法
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

In [12]:
#对数据进行标准化处理
ss = StandardScaler()
X_train = ss.fit_transform(X_train)
X_test = ss.transform(X_test)

In [13]:
#初始化logistic回归器和SGDClassifier
lr = LogisticRegression()

In [14]:
#训练模型
lr.fit(X_train, y_train)

C:\Users\rosehyr\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [15]:
#预测
lr_y_pred = lr.predict(X_test)

In [16]:
from sklearn.metrics import classification_report
#使用logistic自带的评分函数
print('Accuracy of LR Classifier:', lr.score(X_test, y_test))

Accuracy of LR Classifier: 0.9883040935672515

In [17]:
#其他指标
print(classification_report(y_test, lr_y_pred, target_names = ['Benign', 'Malignant']))

              precision    recall  f1-score   support

      Benign       0.99      0.99      0.99       100
   Malignant       0.99      0.99      0.99        71

    accuracy                           0.99       171
   macro avg       0.99      0.99      0.99       171
weighted avg       0.99      0.99      0.99       171